name: Terraform Destroy

on:
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: 'Environment to destroy'
    #     required: true
    #     default: 'dev'
    #     type: choice
    #     options:
    #       - dev
    #       - prod

jobs:
  plan:
    name: Terraform Destroy
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: ./cluster

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Terraform Init
      run: terraform init -backend-config=env/dev/backend.tfvars

    - name: Terraform Destroy
      run: terraform destroy -var-file=env/dev/dev.tfvars -auto-approve -input=false