name: Terraform Provision

on:
  workflow_dispatch:

jobs:
  plan:
    name: Terraform Plan
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: ./cluster

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Terraform Init
      run: terraform init -backend-config=env/dev/backend.tfvars

    - name: Terraform Plan
      run: terraform plan -var-file=env/dev/dev.tfvars -input=false

  apply:
    name: Terraform Apply (Manual Approval)
    runs-on: self-hosted
    needs: plan
    environment:
      name: dev
    defaults:
      run:
        shell: bash
        working-directory: ./cluster

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform Init
      run: terraform init -backend-config=env/dev/backend.tfvars

    - name: Terraform Apply
      run: terraform apply -var-file=env/dev/dev.tfvars -auto-approve -input=false
